leftnav:
- identifier: 6fe7b50b-8d5d-460d-a8b6-ca0862b37619
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 437fb2b8-60dd-4573-8764-e1c5b0be9e33
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 33cfbea5-0c3c-461e-8362-5a23448319a9
  name: 'Fall 2022 Course '
  pageRef: /external-resources/fall-2022-course-_33cfbea5-0c3c-461e-8362-5a23448319a9
  weight: 30
